# Generated by Django 6.0.5 on 2026-05-25 11:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('type', models.CharField(choices=[('checking', 'Cuenta Corriente'), ('savings', 'Caja de Ahorro'), ('cash', 'Efectivo'), ('credit_card', 'Tarjeta de Crédito')], default='checking', max_length=20, verbose_name='tipo')),
                ('on_budget', models.BooleanField(default=True, verbose_name='en el presupuesto')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='saldo')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='budgets.budget', verbose_name='presupuesto')),
            ],
            options={
                'verbose_name': 'cuenta',
                'verbose_name_plural': 'cuentas',
                'ordering': ['name'],
            },
        ),
    ]
