# Generated by Django 6.0.5 on 2026-05-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('checking', 'Cuenta Corriente'), ('savings', 'Ahorro')], default='checking', max_length=20, verbose_name='tipo'),
        ),
    ]
