services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: chele:dev
    container_name: chele-web-dev
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - RUNSERVER=true
      - DEBUG=true
    volumes:
      - .:/app
      - sqlite_data:/app/db
      - static_volume:/app/staticfiles
    restart: unless-stopped

volumes:
  sqlite_data:
    name: chele_dev_sqlite_data
  static_volume:
    name: chele_dev_static_volume
