# Generated by Django 6.0.5 on 2026-05-25 11:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('limit', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='límite')),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='Negativo = deuda', max_digits=15, verbose_name='saldo actual')),
                ('interest_rate', models.DecimalField(decimal_places=4, help_text='Ej: 0.08 = 8% mensual', max_digits=6, verbose_name='tasa mensual')),
                ('closing_day', models.IntegerField(verbose_name='día de cierre')),
                ('due_day', models.IntegerField(verbose_name='día de vencimiento')),
                ('last_interest_date', models.DateField(blank=True, null=True, verbose_name='último interés calculado')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_cards', to='budgets.budget', verbose_name='presupuesto')),
            ],
            options={
                'verbose_name': 'tarjeta de crédito',
                'verbose_name_plural': 'tarjetas de crédito',
            },
        ),
        migrations.CreateModel(
            name='InterestCharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='monto')),
                ('date', models.DateField(auto_now_add=True, verbose_name='fecha')),
                ('days_overdue', models.IntegerField(verbose_name='días de atraso')),
                ('applied', models.BooleanField(default=False, verbose_name='aplicado')),
                ('credit_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_charges', to='credit_cards.creditcard', verbose_name='tarjeta')),
            ],
            options={
                'verbose_name': 'cargo de interés',
                'verbose_name_plural': 'cargos de intereses',
            },
        ),
    ]
