# Generated by Django 6.0.5 on 2026-06-16 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='interest_rate',
            field=models.DecimalField(decimal_places=4, help_text='Ej: 0.96 = 96% anual (8% mensual)', max_digits=6, verbose_name='tasa anual'),
        ),
    ]
