# Generated by Django 6.0.5 on 2026-05-25 11:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_budgets', to=settings.AUTH_USER_MODEL, verbose_name='dueño')),
            ],
            options={
                'verbose_name': 'presupuesto',
                'verbose_name_plural': 'presupuestos',
            },
        ),
        migrations.CreateModel(
            name='BudgetMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Dueño'), ('editor', 'Editor')], default='editor', max_length=20, verbose_name='rol')),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgets.budget')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'membresía',
                'verbose_name_plural': 'membresías',
                'unique_together': {('user', 'budget')},
            },
        ),
        migrations.AddField(
            model_name='budget',
            name='members',
            field=models.ManyToManyField(related_name='budgets', through='budgets.BudgetMembership', to=settings.AUTH_USER_MODEL, verbose_name='miembros'),
        ),
        migrations.CreateModel(
            name='CategoryGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('sort_order', models.IntegerField(default=0, verbose_name='orden')),
                ('is_income', models.BooleanField(default=False, verbose_name='es ingreso')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_groups', to='budgets.budget', verbose_name='presupuesto')),
            ],
            options={
                'verbose_name': 'grupo de categorías',
                'verbose_name_plural': 'grupos de categorías',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('sort_order', models.IntegerField(default=0, verbose_name='orden')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='oculto')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='budgets.budget', verbose_name='presupuesto')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='budgets.categorygroup', verbose_name='grupo')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyBudget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.IntegerField(verbose_name='mes')),
                ('year', models.IntegerField(verbose_name='año')),
                ('budgeted', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='presupuestado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_budgets', to='budgets.category', verbose_name='categoría')),
            ],
            options={
                'verbose_name': 'presupuesto mensual',
                'verbose_name_plural': 'presupuestos mensuales',
                'unique_together': {('category', 'month', 'year')},
            },
        ),
    ]
