# Generated by Django 6.0.5 on 2026-05-25 11:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('personal', 'Personal'), ('hipotecario', 'Hipotecario'), ('automotor', 'Automotor'), ('estudiantil', 'Estudiantil'), ('otros', 'Otros')], max_length=20, verbose_name='tipo')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='monto total')),
                ('interest_rate', models.DecimalField(decimal_places=4, help_text='Ej: 0.03 = 3% mensual', max_digits=6, verbose_name='tasa mensual')),
                ('remaining_balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='saldo pendiente')),
                ('total_installments', models.IntegerField(verbose_name='total cuotas')),
                ('paid_installments', models.IntegerField(default=0, verbose_name='cuotas pagadas')),
                ('start_date', models.DateField(verbose_name='fecha inicio')),
                ('next_due_date', models.DateField(verbose_name='próximo vencimiento')),
                ('installment_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='valor cuota')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='budgets.budget', verbose_name='presupuesto')),
            ],
            options={
                'verbose_name': 'préstamo',
                'verbose_name_plural': 'préstamos',
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.IntegerField(verbose_name='número')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='monto')),
                ('due_date', models.DateField(verbose_name='fecha vencimiento')),
                ('paid', models.BooleanField(default=False, verbose_name='pagada')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='fecha pago')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='loans.loan', verbose_name='préstamo')),
            ],
            options={
                'verbose_name': 'cuota',
                'verbose_name_plural': 'cuotas',
                'ordering': ['number'],
            },
        ),
    ]
