# Generated by Django 6.0.5 on 2026-05-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('completed', 'Finalizado')], default='active', max_length=20, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=4, help_text='Ej: 0.36 = 36% anual', max_digits=6, verbose_name='tasa anual'),
        ),
    ]
