# Generated by Django 6.0.5 on 2026-05-25 11:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('budgets', '0001_initial'),
        ('payees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='monto')),
                ('frequency', models.CharField(choices=[('weekly', 'Semanal'), ('biweekly', 'Quincenal'), ('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('yearly', 'Anual')], max_length=20, verbose_name='frecuencia')),
                ('next_date', models.DateField(verbose_name='próxima fecha')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='cuenta')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='budgets.budget', verbose_name='presupuesto')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budgets.category', verbose_name='categoría')),
                ('payee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payees.payee', verbose_name='beneficiario')),
            ],
            options={
                'verbose_name': 'programación',
                'verbose_name_plural': 'programaciones',
            },
        ),
    ]
