# Generated by Django 6.0.5 on 2026-05-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='skip_weekends',
            field=models.BooleanField(default=False, verbose_name='saltar fines de semana'),
        ),
    ]
