# Generated by Django 6.0.5 on 2026-06-16 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_schedule_skip_weekends'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='direction',
            field=models.CharField(choices=[('expense', 'Gasto'), ('income', 'Ingreso')], default='expense', max_length=10, verbose_name='dirección'),
        ),
    ]
