# Generated by Django 6.0.5 on 2026-06-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_schedule_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='apply_before_weekend',
            field=models.BooleanField(default=False, verbose_name='aplicar antes del finde (pasar al viernes)'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='skip_weekends',
            field=models.BooleanField(default=False, verbose_name='saltar fines de semana (pasar al lunes)'),
        ),
    ]
