# Generated by Django 6.0.5 on 2026-05-25 11:39

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('goal_type', models.CharField(choices=[('monthly', 'Ahorro mensual'), ('target_balance', 'Saldo objetivo'), ('target_date', 'Objetivo con fecha'), ('true_expense', 'Gasto anual')], max_length=20, verbose_name='tipo de meta')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='monto')),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='fecha objetivo')),
                ('frequency', models.IntegerField(default=12, verbose_name='frecuencia (meses)')),
                ('is_completed', models.BooleanField(default=False, verbose_name='completada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='budgets.category', verbose_name='categoría')),
            ],
            options={
                'verbose_name': 'meta',
                'verbose_name_plural': 'metas',
            },
        ),
    ]
