# Generated by Django 6.0.5 on 2026-06-26 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='refill_up_to',
            field=models.BooleanField(default=False, verbose_name='completar hasta (refill)'),
        ),
        migrations.AddField(
            model_name='goal',
            name='snooze_month',
            field=models.IntegerField(blank=True, null=True, verbose_name='mes de pausa'),
        ),
        migrations.AddField(
            model_name='goal',
            name='snooze_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='año de pausa'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.CharField(choices=[('monthly', 'Ahorro mensual'), ('yearly', 'Ahorro anual'), ('target_balance', 'Saldo objetivo'), ('target_date', 'Objetivo con fecha'), ('true_expense', 'Gasto anual')], max_length=20, verbose_name='tipo de meta'),
        ),
    ]
