# Generated by Django 6.0.5 on 2026-05-25 11:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgets', '0001_initial'),
        ('payees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('condition_field', models.CharField(choices=[('payee', 'Beneficiario'), ('amount', 'Monto'), ('notes', 'Notas')], max_length=20, verbose_name='campo')),
                ('condition_operator', models.CharField(choices=[('contains', 'contiene'), ('equals', 'es igual a'), ('starts_with', 'empieza con'), ('greater_than', 'mayor que'), ('less_than', 'menor que')], max_length=20, verbose_name='operador')),
                ('condition_value', models.CharField(max_length=500, verbose_name='valor')),
                ('action_notes', models.CharField(blank=True, max_length=500, verbose_name='asignar notas')),
                ('sort_order', models.IntegerField(default=0, verbose_name='orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budgets.category', verbose_name='asignar categoría')),
                ('action_payee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payees.payee', verbose_name='asignar beneficiario')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='budgets.budget', verbose_name='presupuesto')),
            ],
            options={
                'verbose_name': 'regla',
                'verbose_name_plural': 'reglas',
                'ordering': ['sort_order'],
            },
        ),
    ]
